AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM & PHP template using bref.
Resources:
  MainFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Layers: ["arn:aws:lambda:eu-west-1:209497400698:layer:php-80:9"]
      Handler: main.php
      Runtime: provided.al2
      Events:
        Main:
          Type: Api
          Properties:
            Path: /
            Method: ANY
Outputs:
  API:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
